const exercises=[
{id:'PV-MAT-001',name:'Breathing',level:'Fundamental',family:'Respiração e consciência',objective:'Controle respiratório, pelve neutra e percepção corporal.',regions:'Tórax, cervical e pelve',metrics:'Ritmo, alinhamento cabeça-pelve e estabilidade',safety:'Baixo',views:'Anterior e lateral'},
{id:'PV-MAT-003',name:'Cat Stretch',level:'Fundamental',family:'Articulação da coluna',objective:'Mobilidade segmentar e controle escapular.',regions:'Coluna, escápulas e cervical',metrics:'Flexão/extensão, controle escapular e cervical',safety:'Baixo',views:'Lateral'},
{id:'PV-MAT-004',name:'Hundred',level:'Intermediário',family:'Centro / Powerhouse',objective:'Aquecimento, controle central e resistência.',regions:'Coluna torácica, quadril, joelhos e ombros',metrics:'Ângulo tronco-coxa, pelve e ritmo dos braços',safety:'Moderado',views:'Anterior e lateral'},
{id:'PV-MAT-005',name:'Roll Up',level:'Intermediário',family:'Articulação da coluna',objective:'Flexão sequencial e controle abdominal.',regions:'Coluna torácica, lombar e quadril',metrics:'Curva do tronco, velocidade e compensação do quadril',safety:'Moderado',views:'Lateral'},
{id:'PV-MAT-006',name:'Roll Over',level:'Avançado',family:'Articulação da coluna',objective:'Flexão global, controle excêntrico e mobilidade posterior.',regions:'Cervical, lombar e quadril',metrics:'Controle cervical, pelve e ângulo do quadril',safety:'Alto',views:'Lateral'},
{id:'PV-MAT-007',name:'Single Leg Circle',level:'Intermediário',family:'Quadril e membros inferiores',objective:'Mobilidade do quadril com estabilidade pélvica.',regions:'Pelve e quadril',metrics:'Amplitude do quadril e estabilidade pélvica',safety:'Baixo',views:'Anterior e lateral'},
{id:'PV-MAT-009',name:'Single Leg Stretch',level:'Intermediário',family:'Centro / Powerhouse',objective:'Controle central, dissociação dos membros inferiores e coordenação.',regions:'Coluna, pelve e quadril',metrics:'Ângulo do tronco, troca das pernas e estabilidade pélvica',safety:'Moderado',views:'Anterior e lateral'},
{id:'PV-REF-001',name:'Footwork no Reformer',level:'Fundamental',family:'Quadril e membros inferiores',objective:'Alinhamento, força e controle do retorno.',regions:'Pelve, quadril, joelhos e tornozelos',metrics:'Eixo joelho-pé, simetria, amplitude e cadência',safety:'Baixo',views:'Anterior e lateral'}];
const state={part:'L4–L5',case:'mechanical',exercise:exercises[0],view:0,motion:'flex'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const parts={'L2–L3':['Segmento intermediário da região lombar, importante na distribuição progressiva de carga.','Moderada','Moderada'],'L4–L5':['Região de alta demanda mecânica, relevante para mobilidade lombar e transferência de cargas.','Alta','Alta'],'L5–S1':['Junção lombossacra entre a coluna móvel e a base sacral, sujeita a forças de cisalhamento.','Moderada','Muito alta']};
const cases={mechanical:['Lombalgia mecânica','Observe como flexão, extensão e controle muscular modificam a demanda sobre os segmentos inferiores.'],radicular:['Dor radicular L5','Explore o trajeto neural e associe sintomas ao exame, sem assumir causalidade isolada.'],stenosis:['Estenose lombar','Compare a resposta didática em extensão e flexão e discuta a influência da postura.']};
function setScreen(id){$$('.screen,.nav').forEach(x=>x.classList.toggle('active',x.id===id||x.dataset.screen===id));$('#title').textContent={anatomy:'Exploração lombar',pilates:'Biblioteca PilatesVision',tutor:'Tutor contextual'}[id];scrollTo({top:0,behavior:'smooth'})}
$$('.nav').forEach(b=>b.onclick=()=>setScreen(b.dataset.screen));
function move(){let n=+$('#range').value,t='perspective(900px) rotateY('+state.view+'deg)';$('#angle').textContent=n+'°';if(state.motion==='flex')t+=' rotateZ('+(n/5)+'deg)';if(state.motion==='lateral')t+=' skewX('+(n/5)+'deg)';if(state.motion==='rotation')t+=' rotateY('+n+'deg)';$('#spine').style.transform=t}
$('#range').oninput=move;$('#reset').onclick=()=>{$('#range').value=0;move()};
$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.view=+b.dataset.view;move()});
$$('[data-motion]').forEach(b=>b.onclick=()=>{$$('[data-motion]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.motion=b.dataset.motion;$('#motionLabel').textContent={flex:'Flexão / extensão',lateral:'Inclinação lateral',rotation:'Rotação axial'}[state.motion];move()});
$$('[data-layer]').forEach(b=>b.onclick=()=>{$$('[data-layer]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#spine').className=b.dataset.layer});
$$('[data-part]').forEach(b=>b.onclick=()=>{state.part=b.dataset.part;$$('[data-part]').forEach(x=>x.classList.toggle('active',x===b));const p=parts[state.part];$('#partTitle').textContent='Segmento '+state.part;$('#partText').textContent=p[0];$('#mobility').textContent=p[1];$('#load').textContent=p[2];updateContext()});
$('#case').onchange=e=>{state.case=e.target.value;$('#caseText').textContent=cases[state.case][1];updateContext()};
function updateContext(){$('#context').textContent=state.part+' · '+cases[state.case][0]}
function renderList(){const q=$('#search').value.toLowerCase(),l=$('#level').value,items=exercises.filter(e=>(l==='all'||e.level===l)&&JSON.stringify(e).toLowerCase().includes(q));$('#list').innerHTML=items.map(e=>'<button class="exercise-card '+(e.id===state.exercise.id?'active':'')+'" data-ex="'+e.id+'"><code>'+e.id+'</code><h3>'+e.name+'</h3><p>'+e.objective+'</p><div class="tags"><span>'+e.level+'</span><span>'+e.family+'</span></div></button>').join('')||'<p>Nenhum exercício encontrado.</p>';$$('[data-ex]').forEach(b=>b.onclick=()=>{state.exercise=exercises.find(e=>e.id===b.dataset.ex);renderList();renderDetail()})}
function renderDetail(){const e=state.exercise;$('#exercise').innerHTML='<em>'+e.id+'</em><h2>'+e.name+'</h2><p>'+e.objective+'</p><div class="detail"><div><small>Família</small><b>'+e.family+'</b></div><div><small>Regiões relacionadas</small><b>'+e.regions+'</b></div><div><small>Métricas educacionais</small><b>'+e.metrics+'</b></div><div><small>Nível de atenção</small><b>'+e.safety+'</b></div><div><small>Captura recomendada</small><b>'+e.views+'</b></div></div><button class="primary" id="study">Estudar com o tutor</button>';$('#study').onclick=()=>{setScreen('tutor');ask('Como '+e.name+' se relaciona com '+e.regions+'?')}}
$('#search').oninput=renderList;$('#level').onchange=renderList;
const replies={anatomy:()=>('O segmento '+state.part+' integra a cadeia lombopélvica. '+parts[state.part][0]+' Uma imagem isolada não define a origem dos sintomas.'),movement:()=>('No caso “'+cases[state.case][0]+'”, compare flexão, extensão e controle do tronco. O simulador representa relações didáticas, não forças reais.'),quiz:()=>('Pergunta: quais dados clínicos você combinaria com a exploração de '+state.part+' antes de formular uma hipótese? Considere história, exame neurológico, movimento e sinais de alerta.'),safety:()=>('Este MVP ensina relações entre anatomia e movimento. Não diagnostica, não prescreve e não substitui avaliação profissional. Não insira dados identificáveis.')};
function ask(text,type){$('#messages').insertAdjacentHTML('beforeend','<div class="message user">'+text.replace(/[<>]/g,'')+'</div>');let r=type?replies[type]():text.toLowerCase().includes('teaser')?'No Teaser, coordene flexão torácica, estabilização lombopélvica e alavanca dos membros inferiores. Use regressões e não trate uma métrica isolada como verdade clínica.':replies.movement();setTimeout(()=>{$('#messages').insertAdjacentHTML('beforeend','<div class="message ai">'+r+'</div>');$('#messages').scrollTop=99999},200)}
$$('[data-prompt]').forEach(b=>b.onclick=()=>ask(b.textContent,b.dataset.prompt));$('#chatForm').onsubmit=e=>{e.preventDefault();if($('#chatInput').value.trim())ask($('#chatInput').value.trim());$('#chatInput').value=''};$('#askCase').onclick=()=>{setScreen('tutor');ask('Quero explorar '+cases[state.case][0]+' em '+state.part+'.','movement')};
const dialog=$('dialog');$('#about').onclick=()=>dialog.showModal();$('#close').onclick=()=>dialog.close();renderList();renderDetail();updateContext();move();
